"""empty message

Revision ID: 2fb224f90131
Revises: 38b5e18da25d
Create Date: 2023-10-02 00:28:33.604876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb224f90131'
down_revision = '38b5e18da25d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordered_item', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordered_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'])
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
